import { Eye, EyeOff, LoaderCircle, X } from 'lucide-react'
import { useEffect, useState } from 'react'
import type { RequestMode, SettingsInput, SettingsView } from '../types/electron-api'

interface Props { initial: SettingsView | null; onClose: () => void; onSave: (value: SettingsInput) => Promise<void>; onTest: (value: SettingsInput) => Promise<string> }
export function SettingsDialog({ initial, onClose, onSave, onTest }: Props) {
  const [form, setForm] = useState<SettingsInput | null>(null)
  const [apiKey, setApiKey] = useState('')
  const [showKey, setShowKey] = useState(false)
  const [busy, setBusy] = useState(false)
  const [message, setMessage] = useState('')
  useEffect(() => { if (initial) setForm({ ...initial }) }, [initial])
  if (!form) return null
  const existingSettings = initial ?? { hasApiKey: false }
  const update = <K extends keyof SettingsInput>(key: K, value: SettingsInput[K]) => setForm({ ...form, [key]: value })
  const save = async () => { setBusy(true); setMessage(''); try { await onSave({ ...form, apiKey: apiKey || undefined }); onClose() } catch (error) { setMessage((error as Error).message) } finally { setBusy(false) } }
  const test = async () => { setBusy(true); setMessage(''); try { setMessage(await onTest({ ...form, apiKey: apiKey || undefined })) } catch (error) { setMessage((error as Error).message) } finally { setBusy(false) } }
  return <div className="modal-backdrop" role="presentation"><section className="modal" role="dialog" aria-modal="true" aria-label="Cài đặt API"><div className="modal-title"><div><span className="eyebrow">Cấu hình</span><h2>Cài đặt kết nối AI</h2></div><button className="icon-button" onClick={onClose}><X /></button></div><p className="helper">Khóa của bạn được Electron lưu trong bộ nhớ cục bộ của ứng dụng và không bao giờ trả về trình chỉnh sửa.</p>
    <div className="settings-grid"><label className="field field-wide"><span>Địa chỉ API (base URL)</span><input value={form.endpoint} placeholder="https://api.openai.com/v1" onChange={(e) => update('endpoint', e.target.value)} /></label><label className="field"><span>Mô hình</span><input value={form.model} placeholder="gpt-image-1" onChange={(e) => update('model', e.target.value)} /></label><label className="field"><span>Kiểu yêu cầu API</span><select value={form.requestMode ?? 'auto'} onChange={(e) => update('requestMode', e.target.value as RequestMode)}><option value="auto">Tự động (theo model)</option><option value="images-edits">Images Edits (OpenAI multipart)</option><option value="chat-completions">Chat Completions (Gemini)</option></select></label><label className="field"><span>Kích thước ảnh thẻ</span><select value={form.imageSize} onChange={(e) => update('imageSize', e.target.value as SettingsInput['imageSize'])}><option value="35x45">35 × 45 mm</option><option value="2x2">2 × 2 in</option><option value="4x6">4 × 6 cm</option></select></label><label className="field"><span>Kích thước ảnh AI</span><select value={form.apiImageSize} onChange={(e) => update('apiImageSize', e.target.value as SettingsInput['apiImageSize'])}><option value="auto">auto</option><option value="1024x1024">1024 × 1024</option><option value="1024x1536">1024 × 1536</option><option value="1536x1024">1536 × 1024</option></select></label><label className="field field-wide"><span>Khóa API {existingSettings.hasApiKey && <em>đã lưu</em>}</span><div className="secret-input"><input type={showKey ? 'text' : 'password'} value={apiKey} placeholder={existingSettings.hasApiKey ? 'Để trống để giữ khóa đã lưu' : 'Dán khóa API'} onChange={(e) => setApiKey(e.target.value)} /><button type="button" className="icon-button" onClick={() => setShowKey(!showKey)}>{showKey ? <EyeOff size={17} /> : <Eye size={17} />}</button></div></label><label className="field"><span>Thời gian chờ (miligiây)</span><input type="number" min="5000" max="300000" value={form.timeoutMs} onChange={(e) => update('timeoutMs', Number(e.target.value))} /></label><label className="field field-wide"><span>Tùy chọn tạo ảnh (JSON tùy chọn)</span><textarea className="small-area" value={form.additionalOptions} placeholder={'{"quality":"high"}'} onChange={(e) => update('additionalOptions', e.target.value)} /></label></div>
    <p className="api-note">Ở chế độ <strong>Tự động</strong>, ứng dụng gửi chuẩn OpenAI Images Edits: <code>multipart/form-data</code> tới <code>{'{endpoint}'}/images/edits</code>. Nếu endpoint dùng router Gemini qua Chat Completions (ví dụ model <code>ag/gemini-...</code>), hãy chọn <strong>Chat Completions (Gemini)</strong> để gửi ảnh tham chiếu kèm lời nhắc; không gửi <code>size</code>. Bạn có thể thêm tuỳ chọn Gemini của router dưới dạng các giá trị đơn giản trong JSON nếu router hỗ trợ.</p>{message && <p className="notice">{message}</p>}<div className="modal-actions"><button className="button button-quiet" disabled={busy} onClick={test}>{busy && <LoaderCircle className="spin" size={15} />} Kiểm tra kết nối</button><button className="button button-primary" disabled={busy} onClick={save}>Lưu cài đặt</button></div>
  </section></div>
}
